### ISSUE TITLE
Use of undeclared type MapGenerator and other build errors on Xcode 7

### ISSUE THREAD

**Issue by brendand** [couchbaselabs/Grocery-Sync-iOS#14]
I'm trying to compile the latest version of GrocerySync with Xcode 7 (the bonjour-sync-swift2 branch), but I'm getting a couple of errors.

On line 58 in PeerSet.swift: "use of undeclared type 'MapGenerator':
    `public typealias Generator = MapGenerator<DictionaryGenerator<String, Peer>, Peer>`

On line 13 in PeerSet.swift: "Type PeerSet does not conform to protocol 'SequenceType':
   ` public struct PeerSet : SequenceType, Equatable, CustomStringConvertible {`

On line 61 of FollowViewController.swift: "Ambiguous reference to member 'sort'":
    `self.offlinePeers = peerSyncMgr.offlinePairedPeers.sort({$0.nickname < $1.nickname})`

I'm not super versed in Swift just yet so I am unable to fix these errors myself at the moment. I couldn't find anything on MapGenerator for one thing.

Thanks,

Brendan

**Comment by snej** [comment]
Looks like they changed `MapGenerator` to `LazyMapGenerator`. That one change clears up the errors. I've got a few other tweaks pending too; I'll check them all in soon.

**Comment by brendand** [comment]
Oh wow! I hunted on Google for quite a while looking for MapGenerator and Swift 2, but I didn't see any mention of LazyMapGenerator as a replacement. Thanks for the fix!
