### ISSUE TITLE
503 - DB Server over capacity error adding items

### ISSUE THREAD

**Issue by msywensky** [couchbaselabs/Grocery-Sync-iOS#18]
Built the swift version and ran in simulator.  Attempted to add an item and received the following error.

demo.mobile.couchbase.com/grocery-sync/]: _bulk_docs got an error: {
    error = 503;
    id = "-YNR10TEJ8BT23-e-218r08";
    reason = "Database server is over capacity";
    status = 503;
}

**Comment by snej** [comment]
Your database server is over capacity. This is an issue on the server side, probably a temporary one.

This message isn't part of adding an item, it's part of the replication that pushes recent changes to the server. The document has already been added to the local database. The replicator will keep trying to push the change to the server until it succeeds.
